name: Continuous Deployment
on: [push]

jobs:
  deploy_prod:
   name: Deploy to Production
   environment:
     name: Production
     url: https://swissgames.garden
   if: github.ref == 'refs/heads/master'
   runs-on: ubuntu-latest
   env:
     PRIVATE_SSH_KEY: ${{ secrets.PRIVATE_SSH_KEY }}
   steps:
     - uses: actions/checkout@v3
     - uses: ./.github/actions/deploy
       with:
         stage: production
         ssh_private_key: ${{ secrets.PRIVATE_SSH_KEY }}

  deploy_staging:
   name: Deploy to Staging
   environment:
     name: Staging
     url: https://staging.swissgames.garden
   if: github.ref == 'refs/heads/feature/rework-deployment-env'
   runs-on: ubuntu-latest
   env:
     PRIVATE_SSH_KEY: ${{ secrets.PRIVATE_SSH_KEY }}
   steps:
     - uses: actions/checkout@v3
     - uses: ./.github/actions/deploy
       with:
         stage: staging
         ssh_private_key: ${{ secrets.PRIVATE_SSH_KEY }}
